print("Michael's Dad is a Police officer")
print("Yetunde's Family will be meeting with \"The Samsom\" Family to discuss the engagement")
print("We will be visiting Daniel's Father for contract")
print('Moses said that "He will be in church this sunday"')
print("What's the difference between \"Mike" and "Mark\"")
print('The election between the two parties “Mandate” and “Reform Mandate” are highly suspicious')
print("They're more than one way to be a member of the party")
print('He’s either a member of “The Ranger’s Team” or “The Prediator’s Team” but I know he’s not a member of “The Tiger’s Team”.')
print("Where on earth’s core did she met her friend’s mate?")
print("Where are your brother’s friends “John”,  “Jake”,  “Jame” and “Jane” that where sitted here just now?")
